# =============================================================================
# PaySpyre v2 — Supabase Database Setup Script (PowerShell)
# =============================================================================
# This script helps configure the .env.local file for Supabase connection.
# Usage: .\scripts\setup-supabase-env.ps1
#
# You will be prompted for:
# 1. Your Supabase project reference (from URL or dashboard)
# 2. Your database password (from Settings → Database)
# =============================================================================

Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "PaySpyre v2 — Supabase Database Configuration" -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "This script will create/update .env.local with your Supabase credentials."
Write-Host ""
Write-Host "WHERE TO FIND YOUR SUPABASE CREDENTIALS:"
Write-Host "  1. Go to https://supabase.com/dashboard"
Write-Host "  2. Select your project"
Write-Host "  3. Go to Settings → Database"
Write-Host "  4. Your PROJECT_REF is in the project URL or dashboard"
Write-Host "  5. Your database password is set when you created the project"
Write-Host "     (or reset in Settings → Database if you forgot it)"
Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

# Prompt for PROJECT_REF
$PROJECT_REF = Read-Host "Enter your Supabase PROJECT_REF (e.g., abcdefgh1234)"
if ([string]::IsNullOrWhiteSpace($PROJECT_REF)) {
    Write-Host "ERROR: PROJECT_REF is required" -ForegroundColor Red
    exit 1
}

# Prompt for password
$DB_PASSWORD = Read-Host "Enter your Supabase database password" -AsSecureString
$DB_PASSWORD = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($DB_PASSWORD))
if ([string]::IsNullOrWhiteSpace($DB_PASSWORD)) {
    Write-Host "ERROR: Database password is required" -ForegroundColor Red
    exit 1
}

# Build connection string
$CONNECTION_STRING = "postgresql+psycopg2://postgres:${DB_PASSWORD}@db.${PROJECT_REF}.supabase.co:5432/postgres"

# Create .env.local file
@"
# Auto-generated by setup-supabase-env.ps1
# Date: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# Supabase project: ${PROJECT_REF}

DATABASE_URL=${CONNECTION_STRING}
"@ | Out-File -FilePath ".env.local" -Encoding utf8

Write-Host ""
Write-Host "================================================================" -ForegroundColor Green
Write-Host "SUCCESS! .env.local created with Supabase connection string" -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Connection string (redacted):"
Write-Host "  DATABASE_URL=postgresql+psycopg2://postgres:****@db.${PROJECT_REF}.supabase.co:5432/postgres"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Verify .env.local was created correctly"
Write-Host "  2. Run: .\venv\Scripts\Activate.ps1"
Write-Host "  3. Run: alembic current"
Write-Host "  4. Run: alembic upgrade head"
Write-Host ""
Write-Host "================================================================" -ForegroundColor Green
