#!/bin/bash
# =============================================================================
# PaySpyre v2 — Supabase Database Setup Script
# =============================================================================
# This script helps configure the .env.local file for Supabase connection.
# Usage: ./scripts/setup-supabase-env.sh
#
# You will be prompted for:
# 1. Your Supabase project reference (from URL or dashboard)
# 2. Your database password (from Settings → Database)
# =============================================================================

set -e

echo "================================================================"
echo "PaySpyre v2 — Supabase Database Configuration"
echo "================================================================"
echo ""
echo "This script will create/update .env.local with your Supabase credentials."
echo ""
echo "WHERE TO FIND YOUR SUPABASE CREDENTIALS:"
echo "  1. Go to https://supabase.com/dashboard"
echo "  2. Select your project"
echo "  3. Go to Settings → Database"
echo "  4. Your PROJECT_REF is in the project URL or dashboard"
echo "  5. Your database password is set when you created the project"
echo "     (or reset in Settings → Database if you forgot it)"
echo ""
echo "================================================================"
echo ""

# Prompt for PROJECT_REF
read -p "Enter your Supabase PROJECT_REF (e.g., abcdefgh1234): " PROJECT_REF
if [ -z "$PROJECT_REF" ]; then
    echo "ERROR: PROJECT_REF is required"
    exit 1
fi

# Prompt for password
read -s -p "Enter your Supabase database password: " DB_PASSWORD
echo ""
if [ -z "$DB_PASSWORD" ]; then
    echo "ERROR: Database password is required"
    exit 1
fi

# Build connection string
CONNECTION_STRING="postgresql+psycopg2://postgres:${DB_PASSWORD}@db.${PROJECT_REF}.supabase.co:5432/postgres"

# Create .env.local file
cat > .env.local << EOF
# Auto-generated by setup-supabase-env.sh
# Date: $(date)
# Supabase project: ${PROJECT_REF}

DATABASE_URL=${CONNECTION_STRING}
EOF

echo ""
echo "================================================================"
echo "SUCCESS! .env.local created with Supabase connection string"
echo "================================================================"
echo ""
echo "Connection string (redacted):"
echo "  DATABASE_URL=postgresql+psycopg2://postgres:****@db.${PROJECT_REF}.supabase.co:5432/postgres"
echo ""
echo "Next steps:"
echo "  1. Verify .env.local was created correctly"
echo "  2. Run: source venv/Scripts/activate  (or venv/bin/activate on Linux/Mac)"
echo "  3. Run: alembic current"
echo "  4. Run: alembic upgrade head"
echo ""
echo "================================================================"
