"""Admin loan-document surface (WS-B): on-demand generation + the frozen
snapshot list for one loan, and the SignNow hand-off.

Mounted under ``/admin/loans`` next to the servicing routes. Generation always
creates a NEW ``platform_loan_documents`` row (snapshots are immutable —
regenerating never rewrites what a borrower already saw). The booking-time
agreement is generated by ``book_loan``; these endpoints cover regeneration,
ad-hoc kinds (amortization/fee schedule), period statements, and sending the
agreement into the existing SignNow flow (graceful no-op while creds are
absent — expected in simulator/test mode).
"""
from __future__ import annotations

from datetime import date, datetime
from typing import Optional
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status as http_status
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.core.auth import get_current_user, require_roles
from app.db.base import get_db
from app.models.platform.document_template import (
    DOCUMENT_KINDS,
    PlatformLoanDocument,
)
from app.models.platform.loan import PlatformLoan
from app.services import document_engine, integration_mode, loan_lifecycle
from app.services.document_engine import DocumentEngineError

router = APIRouter(dependencies=[Depends(require_roles("admin", "staff"))])


class LoanDocumentSummary(BaseModel):
    id: UUID
    loan_id: UUID
    kind: str
    title: str
    template_id: Optional[UUID] = None
    template_version: Optional[int] = None
    generated_via: str
    created_at: datetime


class LoanDocumentDetail(LoanDocumentSummary):
    body_html: str


class LoanDocumentList(BaseModel):
    documents: list[LoanDocumentSummary]


class GenerateRequest(BaseModel):
    kind: str
    # Required only for kind=account_statement (inclusive period).
    period_start: Optional[date] = None
    period_end: Optional[date] = None


class SendForSignatureResponse(BaseModel):
    loan_id: UUID
    agreement_status: str
    agreement_ref: Optional[str] = None
    # SIMULATOR / LIVE — so the UI labels a simulated send honestly and shows the
    # "Simulate Signing" control only in simulator mode.
    mode: str = "simulator"
    simulated: bool = False


class SimulateSigningResponse(BaseModel):
    loan_id: UUID
    agreement_status: str
    agreement_ref: Optional[str] = None
    disbursement_status: str
    mode: str = "simulator"
    simulated: bool = True


def _get_loan(db: Session, loan_id: UUID) -> PlatformLoan:
    loan = db.query(PlatformLoan).filter(PlatformLoan.id == loan_id).first()
    if loan is None:
        raise HTTPException(status_code=http_status.HTTP_404_NOT_FOUND, detail="Loan not found")
    return loan


def _summary(d: PlatformLoanDocument) -> LoanDocumentSummary:
    return LoanDocumentSummary(
        id=d.id,
        loan_id=d.loan_id,
        kind=d.kind,
        title=d.title,
        template_id=d.template_id,
        template_version=d.template_version,
        generated_via=d.generated_via,
        created_at=d.created_at,
    )


def _actor_uuid(user) -> Optional[UUID]:
    uid = getattr(user, "id", None)
    return uid if isinstance(uid, UUID) else None


@router.get("/{loan_id}/documents", response_model=LoanDocumentList)
def list_loan_documents(
    loan_id: UUID,
    db: Session = Depends(get_db),
) -> LoanDocumentList:
    """Every generated document snapshot for the loan, newest first."""
    _get_loan(db, loan_id)
    rows = (
        db.query(PlatformLoanDocument)
        .filter(PlatformLoanDocument.loan_id == loan_id)
        .order_by(PlatformLoanDocument.created_at.desc())
        .all()
    )
    return LoanDocumentList(documents=[_summary(d) for d in rows])


@router.get("/{loan_id}/documents/{document_id}", response_model=LoanDocumentDetail)
def get_loan_document(
    loan_id: UUID,
    document_id: UUID,
    db: Session = Depends(get_db),
) -> LoanDocumentDetail:
    _get_loan(db, loan_id)
    d = (
        db.query(PlatformLoanDocument)
        .filter(
            PlatformLoanDocument.id == document_id,
            PlatformLoanDocument.loan_id == loan_id,
        )
        .first()
    )
    if d is None:
        raise HTTPException(status_code=http_status.HTTP_404_NOT_FOUND, detail="Document not found")
    return LoanDocumentDetail(**_summary(d).model_dump(), body_html=d.body_html)


@router.post(
    "/{loan_id}/documents/generate",
    response_model=LoanDocumentDetail,
    status_code=http_status.HTTP_201_CREATED,
)
def generate_loan_document(
    loan_id: UUID,
    body: GenerateRequest,
    db: Session = Depends(get_db),
    user=Depends(get_current_user),
) -> LoanDocumentDetail:
    """Generate a document of ``kind`` on demand (a new immutable snapshot).

    ``account_statement`` additionally requires ``period_start``/``period_end``
    and reuses the servicing statement engine for the figures.
    """
    if body.kind not in DOCUMENT_KINDS:
        raise HTTPException(
            status_code=422, detail=f"kind must be one of {list(DOCUMENT_KINDS)}"
        )
    loan = _get_loan(db, loan_id)
    try:
        if body.kind == "account_statement":
            if body.period_start is None or body.period_end is None:
                raise HTTPException(
                    status_code=422,
                    detail="account_statement requires period_start and period_end",
                )
            if body.period_end < body.period_start:
                raise HTTPException(
                    status_code=422, detail="period_end must be >= period_start"
                )
            doc = document_engine.generate_statement_document(
                db,
                loan,
                body.period_start,
                body.period_end,
                generated_via="on_demand",
                created_by=_actor_uuid(user),
            )
        else:
            doc = document_engine.generate_loan_document(
                db,
                loan,
                body.kind,
                generated_via="on_demand",
                created_by=_actor_uuid(user),
            )
    except DocumentEngineError as exc:
        raise HTTPException(status_code=http_status.HTTP_409_CONFLICT, detail=str(exc))
    return LoanDocumentDetail(**_summary(doc).model_dump(), body_html=doc.body_html)


@router.post("/{loan_id}/documents/send-for-signature", response_model=SendForSignatureResponse)
def send_for_signature(
    loan_id: UUID,
    db: Session = Depends(get_db),
) -> SendForSignatureResponse:
    """Send the loan agreement into the e-sign flow.

    Delegates to the hardened ``loan_lifecycle.send_agreement`` entry point
    (forward-only, idempotent).

    MODE-AWARE (Dave's Integration SIMULATOR mandate): in SIMULATOR mode this
    really transitions the agreement to ``sent`` (awaiting signature) with a
    labelled simulated ref, so the flow can be reviewed and then completed via
    ``simulate-signing``. In LIVE mode it fires the real SignNow invite (a
    graceful no-op if creds are absent — live is gated behind credentials).
    """
    loan = _get_loan(db, loan_id)
    loan = loan_lifecycle.send_agreement(db, loan)
    mode = integration_mode.resolve_mode(db, "signnow")
    return SendForSignatureResponse(
        loan_id=loan.id,
        agreement_status=loan.agreement_status,
        agreement_ref=loan.agreement_ref,
        mode=mode,
        simulated=bool(
            loan.agreement_ref
            and loan.agreement_ref.startswith(loan_lifecycle.SIMULATED_AGREEMENT_REF_PREFIX)
        ),
    )


@router.post("/{loan_id}/documents/simulate-signing", response_model=SimulateSigningResponse)
def simulate_signing(
    loan_id: UUID,
    db: Session = Depends(get_db),
) -> SimulateSigningResponse:
    """Complete a SIMULATED e-signature (the "Simulate Signing" button backend).

    Simulator mode only — drives the SAME state transition the real SignNow
    completion webhook drives (``agreement → signed`` then the disbursement
    entry point) so the loan can proceed. Rejected 409 when SignNow is in LIVE
    mode (the real signing flow applies there). The result is labelled
    ``simulated: true``.
    """
    loan = _get_loan(db, loan_id)
    try:
        loan = loan_lifecycle.simulate_signing(db, loan)
    except loan_lifecycle.ESignModeError as exc:
        raise HTTPException(status_code=http_status.HTTP_409_CONFLICT, detail=str(exc))
    return SimulateSigningResponse(
        loan_id=loan.id,
        agreement_status=loan.agreement_status,
        agreement_ref=loan.agreement_ref,
        disbursement_status=loan.disbursement_status,
        mode=integration_mode.resolve_mode(db, "signnow"),
        simulated=True,
    )
